kind: ConfigMap
apiVersion: v1
metadata:
  name: db-config
data:
  username: sa
  url: jdbc:h2:mem:ordersdb
  password: password
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: order-microservice-cm
data:
  application-dev.yaml: |-
    app:
        orderCount: 10
    server:
      port: 8222
    logging:
      level:
        root: INFO 
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_mJ4ZUJIkC
    aws:
      region: ap-south-1
      topic-arn: arn:aws:sns:ap-south-1:831955480324:order-events

      datasource:
        url: jdbc:h2:mem:orders_db
        username: sa
        password: welcome
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
            format_sql: true
    info:
      app:
        name: orders-api
        description: API for managing orders
        version: 1.0.0
    management:
      prometheus:
        metrics:
          export:
            descriptions: true
            enabled: true
      endpoint:
        health:
          show-details: "ALWAYS"
          probes:
            enabled: true
        circuitbreakers:
          enabled: true 
      endpoints:
        web:
          exposure:
            include: "*"
      info:
        env:
          enabled: true     
      health:
        circuitbreakers:
          enabled: true
        defaults:
          enabled: true

    # Resilience4j Circuit Breaker Configuration
    resilience4j:
      circuitbreaker:
        configs:
          default:
            registerHealthIndicator: true
            sliding-window-type: COUNT_BASED
        instances:
          inventoryservice:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 10s
            permittedNumberOfCallsInHalfOpenState: 3
            automatic-transition-from-open-to-half-open-enabled: true
            eventConsumerBufferSize: 10
            recordExceptions:
              - org.springframework.web.client.HttpServerErrorException
              - java.io.IOException
              - org.springframework.web.reactive.function.client.WebClientRequestException

  application-qa.yaml: |-
    app:
        orderCount: 10
    server:
      port: 8333
    logging:
      level:
        root: INFO
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_mJ4ZUJIkC
    aws:
      region: ap-south-1
      topic-arn: arn:aws:sns:ap-south-1:831955480324:order-events

      datasource:
        url: jdbc:h2:mem:orders_db
        username: sa
        password: welcome
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
            format_sql: true
    info:
      app:
        name: orders-api
        description: API for managing orders
        version: 1.0.0
    management:
      prometheus:
        metrics:
          export:
            descriptions: true
            enabled: true
      endpoint:
        health:
          show-details: "ALWAYS"
          probes:
            enabled: true
        circuitbreakers:
          enabled: true 
      endpoints:
        web:
          exposure:
            include: "*"
      info:
        env:
          enabled: true     
      health:
        circuitbreakers:
          enabled: true
        defaults:
          enabled: true

    # Resilience4j Circuit Breaker Configuration
    resilience4j:
      circuitbreaker:
        configs:
          default:
            registerHealthIndicator: true
            sliding-window-type: COUNT_BASED
        instances:
          inventoryservice:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 10s
            permittedNumberOfCallsInHalfOpenState: 3
            automatic-transition-from-open-to-half-open-enabled: true
            eventConsumerBufferSize: 10
            recordExceptions:
              - org.springframework.web.client.HttpServerErrorException
              - java.io.IOException
              - org.springframework.web.reactive.function.client.WebClientRequestException


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice-dep
  labels:
    app: order-microservice-dep
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
      - name: order-microservice
        image: classpathio/order-microservice
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: password
        volumeMounts:
        - name: app-config
          mountPath: /app/config 
          readOnly: true
        ports:
        - name: app
          containerPort:  8222
          protocol: TCP
      volumes:
      - name: app-config
        configMap:
          name: order-microservice-cm
--- 
apiVersion: v1
kind: Service
metadata:
  name: order-microservice-svc
spec:
  selector:
    app: order-microservice
  type: ClusterIP
  ports:
  - name: order-microservice
    protocol: TCP
    port: 80 
    targetPort: 8222
        